gaussian_dim: 3
time_duration: [0.0, 0.0]
num_pts: 300_000
num_pts_ratio: 1.0
rot_4d: False # 3d 为 false
force_sh_3d: False # 3d 为 false
batch_size: 1
exhaust_test: True
exp_name: 'bear'
chkpnt_path: 'output/test3d/bear/chkpnt_best.pth'
# cache_path: 'output/'

ModelParams:
  sh_degree: 3
  source_path: "data/bear"
  model_path: "output/test3d/bear"
  images: "images"
  resolution: 4           # 目前显存不太够
  white_background: False
  data_device: "cuda"
  eval: True
  extension: ".png"
  num_extra_pts: 0
  loaded_pth: ""
  frame_ratio: 1
  dataloader: False
  # edit
  edit_task: True
  num_frames: 2
  # segment
  num_classes: 256
  objects: "object_mask"

PipelineParams:
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: True
  env_map_res: 500
  env_optimize_until: 5000
  env_optimize_from: 0
  eval_shfs_4d: True

OptimizationParams:
  iterations: 30_000
  position_lr_init: 0.00016
  position_t_lr_init: -1.0
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30_000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  thresh_opa_prune: 0.005
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15_000
  densify_grad_threshold: 0.0002
  densify_grad_t_threshold: 0.0002 / 40 # 想办法用上
  densify_until_num_points: -1
  final_prune_from_iter: -1
  sh_increase_interval: 1000
  lambda_opa_mask: 0.0
  lambda_rigid: 0.0
  lambda_motion: 0.0
  reg3d_interval: 5
  reg3d_k: 5
  reg3d_lambda_val: 2
  reg3d_max_points: 200000
  reg3d_sample_size: 1000